import Head from 'next/head'
import Header from '@/components/@header/Header'
import ContentLayout from '@/layouts/ContentLayout'

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      

      <Header/>

      <ContentLayout />
    </>
  )
}
