import Head from 'next/head'

import LoginForm from '@/components/@loginForm/LoginForm'

export default function Home() {
  return (
    <>
      <Head>
        <title>Arias & Asociados</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      

      <LoginForm />
    </>
  )
}
